### ISSUE TITLE
Create db schema, models and seeder logic

### ISSUE THREAD

**Issue by mimidotsuser** [mimidotsuser/ecommerce-php#1]
## Tasks
Create database schema through migrations as follows:
- [x] 	Create user table migration 
- [x] Create roles table migration
- [x] Create user roles table migration
- [x] Create products table migration

Create seeder logic
- [x] Add user,role,user role, and product models + define relationships
- [x] Add user seeder factory
- [x] Add role seeder factory
- [x] Add product seeder factory
- [x] Add bulk data seeder logic
