### ISSUE TITLE
Provide mechanism for user account registration 

### ISSUE THREAD

**Issue by mimidotsuser** [mimidotsuser/ecommerce-php#2]
As some endpoints should only be accessed by authenticated user, provide a way to create a user account.

### Tasks

- [x] Add endpoint for registration `/api/v1/register`
- [x] Add logic to validate request data
- [x] Add logic to create user account

### Tests
- [x] Invalid create user request data should return  bad request error
- [x] New user can register successfully
- [x] Account should not create a user if they already exists (identified by email)  
- [x] New user registered through the endpoint is assigned customer role only
- [x] Assert user persistent password is secured
