### ISSUE TITLE
Provide mechanism for user authentication

### ISSUE THREAD

**Issue by mimidotsuser** [mimidotsuser/ecommerce-php#3]
As some endpoints should only be accessed by authenticated user, provide a way to authenticate a user.

### Tasks

- [x] Add endpoint for login `/api/v1/login`
- [x] Add logic to validate request data
- [x] Add logic to compare credentials
- [x] Add logic to generate JWT token

### Tests
- [x] Invalid login request data should return `400` bad request error
- [x] Existing users with correct credentials can authenticate successfully
- [ ] Valid JWT token is return on successful authentication
