### ISSUE TITLE
User account management

### ISSUE THREAD

**Issue by mimidotsuser** [mimidotsuser/ecommerce-php#4]
Admin should be able to manage user account details

### Tasks

- [x] Add endpoint and logic for creating new user account `/api/v1/users/new`
- [x] Add endpoint and logic to retrieve all users `/api/v1/users/show`
- [x] Add endpoint and logic to update existing user details `/api/v1/users/update/:id`
- [x] Add endpoint and logic to delete user account `/api/v1/users/delete/:id`
- [x] Create a gate to ensure only admin can access above endpoints

### Tests
- [x] Only authenticated user can access the endpoints resource
- [x] Only admin can access the endpoints resource
- [x] User can be created through appropriate endpoint successfully 
- [x] User account details can be updated through appropriate endpoint successfully 
- [x] User account details can be retrieved through appropriate endpoint successfully 
- [x] User account can be deleted successfully 
- [x] Invalid data submitted to the **endpoints** returns 400 bad request or 404 not found response 
- [x] Reject duplication of user account data

**Note** User password should not be exposed even if encrypted
