### ISSUE TITLE
User roles management

### ISSUE THREAD

**Issue by mimidotsuser** [mimidotsuser/ecommerce-php#5]
Admin should be able to manage roles

### Tasks

- [x] Add endpoint and logic for creating new role `/api/v1/roles/new`
- [x] Add endpoint and logic to retrieve all existing roles `/api/v1/roles/show`
- [x] Add endpoint and logic to update existing role details `/api/v1/roles/update/:id`
- [x] Add endpoint and logic to delete role `/api/v1/roles/delete/:id`.
- [x] Create a gate to ensure only admin can access above endpoints
- [x] Role should only be deleted if it there is no user assigned to the same

### Tests
- [x] Only authenticated user can access the endpoints resource
- [x] Only admin can access the endpoints resource
- [x] Role can be created through appropriate endpoint successfully 
- [x] Role details can be updated through appropriate endpoint successfully 
- [x] Role details can be retrieved through appropriate endpoint successfully 
- [x] Role can be deleted successfully if there is no user assigned to the role
- [x] Role cannot be deleted if there is a user assigned to the role
- [x] Invalid data submitted to the **endpoints** returns 400 bad request or 404 not found response 
- [x] Reject duplication of role data
