### ISSUE TITLE
Admin product resource management

### ISSUE THREAD

**Issue by mimidotsuser** [mimidotsuser/ecommerce-php#6]
Admin should be able to create, view, update, and delete a product

### Tasks
- [x] Add endpoint and logic for creating new product `/api/v1/products/new` _renamed from /products/_
- [x] Add endpoint and logic to retrieve all existing product `/api/v1/products/show`
- [x] Add endpoint and logic to update existing product details `/api/v1/products/update/:id`
- [x] Add endpoint and logic to delete a product `/api/v1/products/delete/:id`.
- [x] Add endpoint and logic to search a product `/api/v1/products/search`. _(search using either name or price using POST method)_
- [x] Create authorization policy where:
    - [x] Admin or customer can create a product
    - [x] Only admin can update a product
    - [x] Admin can view all products
    - [x]  Customer can only view products they created
    - [x]  Customer can search a product
    - [x]  Only admin can delete a product

### Tests
- [x] Only authenticated user can access the endpoints resource
- [ ] Customer and admin can create a product
- [ ] Admin can view all products
- [ ] Customer cannot view others products
- [ ] Customer can view their products
- [ ] Only admin can update product details
- [ ] Only admin can delete a product
- [ ] Only customer can search a product *
- [ ]  Customer can only search their products *
- [ ] Invalid request data to the **endpoints** returns 403 unauthorized, 400 bad request, or 404 not found response 
- [ ] Reject duplication of product data

**Note**  product price = quantity * unit cost
